---
 - name: install docker engine related package
   apt: name={{ item }} state=present
   with_items:
      - apt-transport-https 
      - ca-certificates

 - name: add apt source list
   command: sh -c "echo 'deb https://apt.dockerproject.org/repo debian-jessie main' > /etc/apt/sources.list.d/docker.list"

 - name: add new gpg key
   command: sh -c "apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D"

 - name: apt-get update && apt-get upgrade
   apt: update_cache=yes upgrade=yes

 - name: install docker engine 
   apt: name={{ item }} state=present
   with_items:
      - docker-engine

 - name: docker runnning and enabled
   service: name=docker state=running enabled=yes

